version: 2

project_name: ishell

builds:
  - id: ishell
    main: .
    binary: ishell
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.appVersion={{ .Version }}

archives:
  - id: binaries
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  prerelease: auto
